[package]
name = "autonix"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
walkdir = "2.5.0"
clap = { version = "4.5", features = ["derive"] }
toml = "0.8"
regex = "1.10"

[dev-dependencies]
tempfile = "3.24"
